// Devin "Lauren" Elder
// VFW Term 1212
// Project 3
// 12/6/2012

var json = {
	"contact1": {
		"userName": ["Username: ", "Snooky"],
		"age": ["Age: ", "28"],
		"city": ["City: ", "Lakeland"],
		"website": ["Dating Website: ", "Pof.com"],
		"contacted": ["First Contacted: ", "03/13/2012"],
		"gender": ["Gender: ", "Female"],
		"orientation": ["Sexual Orientation: ", "Bisexual"],
		"vehicle": ["Has a Vehicle: ", "Yes"],
		"interests": ["Has Shared Interests: ", "No"],
		"stable": ["Is Financially Stable: ", "Yes"],
		"drinks": ["Drinks: ", "Yes"],
		"smokes": ["Smokes: ", "No"],
		"hasKids": ["Has Kids: ", "No"],
		"wantsKids": ["Wants Kids: ", "No"],
		"hasPets": ["Has Pets: ", "No"],
		"music": ["Favorite Music Genre: ", "Dance"],
		"movie": ["Favorite Movie Genre: ", "Horror"],
		"compatible": ["Level of Compatibility: ", "5"],
		"notes": ["Additional Information: ", ""],
	},
	"contact2": {
		"userName": ["Username: ", "Jeff"],
		"age": ["Age: ", "25"],
		"city": ["City: ", "Auburndale"],
		"website": ["Dating Website: ", "Pof.com"],
		"contacted": ["First Contacted: ", "04/18/2012"],
		"gender": ["Gender: ", "Male"],
		"orientation": ["Sexual Orientation: ", "Straight"],
		"vehicle": ["Has a Vehicle: ", "No"],
		"interests": ["Has Shared Interests: ", "No"],
		"stable": ["Is Financially Stable: ", "Yes"],
		"drinks": ["Drinks: ", "No"],
		"smokes": ["Smokes: ", "Yes"],
		"hasKids": ["Has Kids: ", "Yes"],
		"wantsKids": ["Wants Kids: ", "No"],
		"hasPets": ["Has Pets: ", "Yes"],
		"music": ["Favorite Music Genre: ", "Rap"],
		"movie": ["Favorite Movie Genre: ", "Comedy"],
		"compatible": ["Level of Compatibility: ", "10"],
		"notes": ["Additional Information: ", "Boring"],
	},
	"contact3": {
		"userName": ["Username: ", "FoodForThought"],
		"age": ["Age: ", "30"],
		"city": ["City: ", "Davenport"],
		"website": ["Dating Website: ", "Okcupid.com"],
		"contacted": ["First Contacted: ", "07/04/2012"],
		"gender": ["Gender: ", "Female"],
		"orientation": ["Sexual Orientation: ", "Gay"],
		"vehicle": ["Has a Vehicle: ", "Yes"],
		"interests": ["Has Shared Interests: ", "No"],
		"stable": ["Is Financially Stable: ", "Yes"],
		"drinks": ["Drinks: ", "Yes"],
		"smokes": ["Smokes: ", "Yes"],
		"hasKids": ["Has Kids: ", "No"],
		"wantsKids": ["Wants Kids: ", "No"],
		"hasPets": ["Has Pets: ", "Yes"],
		"music": ["Favorite Music Genre: ", "Country"],
		"movie": ["Favorite Movie Genre: ", "Adventure"],
		"compatible": ["Level of Compatibility: ", "15"],
		"notes": ["Additional Information: ", ""],
	}
}